config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resource :cart, only: [:show,:destroy] do
    collection do
      post :add, path: ':id/app'
      # /cart/2/add
      get :checkout
    end
  end

  resources :orders, only:[:index,:show,:create] do
    member do
      put :cancel  # PUT /orders/2/cancel  (刪除訂單) 
      get :pay #/order/12314141/pay
      post :paid
    end
  end


  resources :categories,only:[:show]
  resources :books , only: [:index,:show] do 
    member do 
      post :comment    #/books/:id/comment , to: 'books#comment'
    end
  end
  resources :publishers, only: [:show]
  # resources :comments, only:[:create]

  root 'books#index'

  namespace :admin do
    root 'books#index'  #/admin
    resources :books    #/admin/book
    resources :publishers
    resources :categories, except:[:show]
  end

  namespace :api do
    resources :books, only: [] do
      member do
        post :favorite
      end
    end
  end


  
end

app/views/shared/frontend/_menu.html.erb
<aside class="column is-2 ais-fullheight menu">
  <p class="menu-label">分類</p>
    <ul class="menu-list">
      <% categories.each do |category|%>
        <li><%=link_to category.title,category_path(category)%></li>
        <% end %>
    </ul>
  <p class="menu-label">出版社</p>
    <ul class="menu-list">
      <% publishers.each do |publisher|%>
        <li><%=link_to publisher.name, publisher_path(publisher)%></li>
      <%end%>
    </ul>    
</aside>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar has-shadow" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class: 'navbar-item' do %>
      <i class="fas fa-book"></i>
    <% end %>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "書本列表", books_path, class: 'navbar-item' %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item" data-controller="cart" data-action="ajax:success@window->cart#update">
        <%= link_to cart_path, class: 'button' do %>
          <i class="fas fa-shopping-cart"></i> (<span data-target="cart.items"><%= current_cart.items.count %></span>)
        <% end %>

        <% if user_signed_in? %>
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              <%= current_user.email %>
            </a>

            <div class="navbar-dropdown">
              <%= link_to "我的訂單", orders_path, class: 'navbar-item' %>
              <hr class="navbar-divider">
              <%= link_to "登出", destroy_user_session_path, method: 'delete', class: 'navbar-item' %>
            </div>
          </div>
        <% else %>
          <%= link_to "註冊", new_user_registration_path, class: 'button is-primary' %>
          <%= link_to "登入", new_user_session_path, class: 'button is-light' %>
        <% end %>
      </div>
    </div>
  </div>
  </div>
</nav>