config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resource :cart, only: [:show,:destroy] do
    collection do
      post :add, path: ':id/app'
      # /cart/2/add
      get :checkout
    end
  end

  resources :orders, only:[:index,:show,:create] do
    member do
      put :cancel  # PUT /orders/2/cancel  (刪除訂單) 
      get :pay #/order/12314141/pay
      post :paid
    end
  end


  resources :categories,only:[:show]
  resources :books , only: [:index,:show] do 
    member do 
      post :comment    #/books/:id/comment , to: 'books#comment'
    end
  end
  resources :publishers, only: [:show]
  # resources :comments, only:[:create]

  root 'books#index'

  namespace :admin do
    root 'books#index'  #/admin
    resources :books    #/admin/book
    resources :publishers
    resources :categories, except:[:show]
  end

  namespace :api do
    resources :books, only: [] do
      member do
        post :favorite
      end
    end
  end


  
end

app/views/shared/backend/_navbar.html.erb
<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
<div class="navbar-brand">
    <%= link_to admin_books_path,class: 'navbar-item' do%>
<i class="fas fa-book"></i>
    <%end%>
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
  
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <%=link_to "書本列表",admin_books_path,class: 'navbar-item'%>  
        <%=link_to "出版社",admin_publishers_path,class: 'navbar-item'%>  
        <%=link_to "分類",admin_categories_path,class: 'navbar-item'%>  
        </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <% if user_signed_in? %>
              <%= link_to current_user.email , edit_user_registration_path , class:'button '%>
              <%=link_to "登出", destroy_user_session_path,method:'delete',class: 'button is-light' %>
            <% else%>
              <%= link_to "註冊", new_user_registration_path,class:'button is-primary'%>
              <%= link_to "登入", new_user_session_path,class:'button is-light' %>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </nav>