config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resource :cart, only: [:show,:destroy] do
    collection do
      post :add, path: ':id/app'
      # /cart/2/add
      get :checkout
    end
  end

  resources :orders, only:[:index,:show,:create] do
    member do
      put :cancel  # PUT /orders/2/cancel  (刪除訂單) 
      get :pay #/order/12314141/pay
      post :paid
    end
  end


  resources :categories,only:[:show]
  resources :books , only: [:index,:show] do 
    member do 
      post :comment    #/books/:id/comment , to: 'books#comment'
    end
  end
  resources :publishers, only: [:show]
  # resources :comments, only:[:create]

  root 'books#index'

  namespace :admin do
    root 'books#index'  #/admin
    resources :books    #/admin/book
    resources :publishers
    resources :categories, except:[:show]
  end

  namespace :api do
    resources :books, only: [] do
      member do
        post :favorite
      end
    end
  end


  
end

app/models/cart.rb
class Cart
  def initialize(items = [])
    @items = items #若是放在下面 則會在每次執行時被清空
  end

  def add_item(product_id)
    found_item = @items.find{ |item| item.product_id == product_id}
    if found_item
      found_item.increment!
    else
      @items << CartItem.new(product_id)
    end
    # 找到就+1 找不到就生一個給你
  end

  def empty?
    @items.empty?
  end

  attr_reader :items
  # def items 
  #   @items   
  # end

  def total_price 
    # total = 0
    # @items.each do |item|
    #   total = total + item.total_price
    # end
    # return total
    @items.reduce(0) { |sum,item| sum + item.total_price }
    # reduce 會拿第一個元素當初始值，所以要給他 0 
  end

  def serialize
    result = @items.map { |item|
      {"product_id" => item.product_id, "quantity" => item.quantity}
    }

    # result = []
    # @items.eachh do |item|
    #   result << {"product_id" => item.product_id, "quantity" => item.quantity}
    # end
    { "items" => result }
  end

  def self.from_hash(hash = nil)
    # cart_hash = {
    #   "items" =>[
    #     {"product_id" => 1,"quantity" => 3},
    #     {"product_id" => 2,"quantity" => 2}
    #   ]
    # }
    if hash && hash["items"]
      items = []
      hash["items"].each do |item|
        items << CartItem.new( item["product_id"],item["quantity"])
      end

      Cart.new(items)
    else
      # 新車
      Cart.new
    end

  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, only: [:checkout]
  layout 'book'
  
  def add
    current_cart.add_item(params[:id])
    session['cart9527'] = current_cart.serialize

    redirect_to root_path, notice: '成功加入購物車'
  end

  def show
  end
  
  def destroy
    session['cart9527'] = nil
    redirect_to root_path, notice: '已清空'
  end

  def checkout
    @order = Order.new
  end
end
                         

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<% if cart.empty?%>
  <article class="message">
    <div class="message-body">
      目前購物車是空的喔！
    </div>
  </article>
<%else%>
<table class="table is-fullwidth">
  <thead>
    <tr>
      <th>商品名稱</th>
      <th>數量</th>
      <th>單價</th>
      <th>小計</th>
    </tr>
  </thead>
  <tbody>
    <% cart.items.each do |item|%>
    <tr>
      <td><%= item.product.title%></td>
      <td><%= item.quantity%></td>
      <td><%= item.product.sell_price%></td>
      <td><%= item.total_price%></td>
    </tr>
    <%end%>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="3">總價</td>
      <td><%= cart.total_price%></td>
    </tr>
  </tfoot>
</table>
<% end %>

app/views/carts/checkout.html.erb
<h1 class="title">結帳</h1>

<%= render 'cart',cart:current_cart%>

<%=form_with(model: @order) do |form|%>
  <div class="field">
    <%=form.label :recipient,"收件人",class: 'label'%>
    <%=form.text_field :recipient,class: 'input'%>
  </div>

  <div class="field">
    <%=form.label :tel,"電話",class: 'label'%>
    <%=form.text_field :tel,class: 'input'%>
  </div>

  <div class="field">
    <%=form.label :address,"地址",class: 'label'%>
    <%=form.text_field :address,class: 'input'%>
  </div>

  <div class="field">
    <%=form.label :note,"說明",class: 'label'%>
    <%=form.text_area :note,class: 'input'%>
  </div>

  <%= form.submit '送出', class: 'button is-primary' %>

<%end%>

app/views/carts/show.html.erb
<h1 class="title"><i class="fas fa-shopping-cart"></i>購物車</h1>

<%= link_to "清空購物車",cart_path,method:'delete',class:'button is-small is light' if not current_cart.empty?%>

<%= render 'cart', cart: current_cart%>

<%= link_to "繼續選購",root_path,class: 'button is-primary'%>
<%= link_to "結帳",checkout_cart_path,class: 'button is-danger' if not current_cart.empty? %>