config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resource :cart, only: [:show,:destroy] do
    collection do
      post :add, path: ':id/app'
      # /cart/2/add
      get :checkout
    end
  end

  resources :orders, only:[:index,:show,:create] do
    member do
      put :cancel  # PUT /orders/2/cancel  (刪除訂單) 
      get :pay #/order/12314141/pay
      post :paid
    end
  end


  resources :categories,only:[:show]
  resources :books , only: [:index,:show] do 
    member do 
      post :comment    #/books/:id/comment , to: 'books#comment'
    end
  end
  resources :publishers, only: [:show]
  # resources :comments, only:[:create]

  root 'books#index'

  namespace :admin do
    root 'books#index'  #/admin
    resources :books    #/admin/book
    resources :publishers
    resources :categories, except:[:show]
  end

  namespace :api do
    resources :books, only: [] do
      member do
        post :favorite
      end
    end
  end


  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  layout 'backend'

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, notice: '建立成功'
    else
      render :new 
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_categories_path, notice: '更新成功'
    else
     render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path,notice: '刪除成功'
  end
  
  private

  def category_params
    params.require(:category).permit(:title)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout 'book'

  def show
    @category = Category.find(params[:id])
    @books = @category.books.page(params[:page])
  end
end

app/views/admin/categories/edit.html.erb
<h1 class="title"> NEWS</h1>

<%=form_with model: [:admin,@category] do |form|%>
<div class="columns">
    <div class="column is-2">
      <div class="field">
        <%= form.label :title, '名稱', class: 'label' %>
        <%= form.text_field :title, class: 'input' %>
      </div>
        <%= form.submit class: 'button is-light' %>
    </div>
</div>
<%end%>

app/views/admin/categories/index.html.erb
<h1 class="title">分類列表</h1>
<%notice%>
<%= link_to '新增咪凹', new_admin_category_path%>
<table>
  <thead>
    <tr>
      <th>分類</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category|%>
    <tr>
      <td><%= link_to category.title,admin_categories_path(category)%></td>
      <td><%= link_to "編輯", edit_admin_category_path(category), class: 'button is-small is-light' %></td>
      <td><%= link_to "刪除", admin_category_path(category), method: :delete, data: { confirm: '確定刪除?!' }, class: 'button is-small is-danger' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/categories/new.html.erb
<h1 class="title"> NEWS</h1>

<%=form_with model: [:admin,@category] do |form|%>
<div class="columns">
    <div class="column is-2">
      <div class="field">
        <%= form.label :title , '名稱', class: 'label' %>
        <%= form.text_field :title, class: 'input' %>
      </div>
        <%= form.submit class: 'button is-light' %>
    </div>
</div>


<%end%>